#!/usr/bin/python
import xmlrpclib
import re
import fileinput
import GeoIP
import ipaddr
import ConfigParser
from optparse import OptionParser


CONFIG_FILE = 'send_secure_to_server.cfg'
config = ConfigParser.RawConfigParser()
config.read(CONFIG_FILE)
server = xmlrpclib.Server(config.get('Default', 'WS_URL'))

def parse_logs(filename):

    try:
        f = open(filename, 'r')
    except:
        raise RuntimeError('ERROR: failed to open file %s' % filename)
        sys.exit(1)

    data = f.readlines()
    if data:

        machine_name = config.get('Default', 'MACHINE')
        rpc_url = config.get('Default', 'WS_URL')
        rpc_username = config.get('Default', 'WS_USERNAME')
        rpc_password = config.get('Default', 'WS_PASSWORD')

        output = server.user_account_log(rpc_username, rpc_password, machine_name, data)
        for line in output:
            print line


parser = OptionParser()
(options, args) = parser.parse_args()

for filename in args:
    parse_logs(filename)
